const ACTIONS = {
  LOAD_FILMS_SUCCESS: 'LOAD_FILMS_SUCCESS',
  LOAD_FILM_SUCCESS: 'LOAD_FILM_SUCCESS',
  SET_SORT_TYPE: 'SET_SORT_TYPE',
  SET_SEARCH_TYPE: 'SET_SEARCH_TYPE',
  LOAD_SEARCH_RESULTS: 'LOAD_SEARCH_RESULTS',
};

export default ACTIONS;
